require('./1Two_Sum_Test');
require('./2Add_Two_Number_Test');
//require('./3Longest_Substring_Without_Repeating_Characters_Test');
require('./7Reverse_Integer_Test');
require('./9Palindrome_Number_Test');
//require('./226Invert_Binary_Tree_Test');
require('./19RNNFEL_Test.js');
require('./20Valid_Parentheses_Test.js');
require('./21Merge_Two_Sorted_Lists_Test');
